config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  # Default page after login (except redirection from email)
  root to: "home#index"

  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  resources :vote, :home, :support, :about
  resources :users
 
  resources :elections do
    resources :proposals 
  end
  resources :proposals do
    resources :options
  end

  # Home
  get '/user' => "home#index", :as => :user_root

  # Election
  get '/elections/:id', to: 'elections#show'
  get '/elections', to: 'elections#index'
  post '/elections', to: 'elections#create'
  get  '/elections/new', to: 'elections#new'
  post '/options', to: 'options#create'
  get '/elections/results/:electionId', to: 'elections#results'
  get '/elections/info/:electionId', to: 'elections#info'
  get '/elections/activate_election/:electionId', to: 'elections#activate_election'

  # Vote
  get '/vote/new/:electionId' => 'vote#new', :as => :email_vote
  get '/elections/results/:electionId' => 'elections#results', :as => :email_results
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/option.rb
class Option < ApplicationRecord
  has_many :votes, dependent: :destroy
  belongs_to :proposal

  validates :description, presence: true
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :authenticate_user!

    def create
      @proposal = Proposal.find(params[:proposal_id])
      @option = @proposal.options.create(option_params)
      redirect_to proposal_path(@proposal)
    end
   
    private
      def option_params
        params.require(:option).permit(:description, :proposal_id)
      end
  
end

app/views/options/_form.html.erb
<%= form_with(model: [ @proposal, @proposal.options.build ], local: true) do |form| %>
  <div class="form-group">
      <%= form.label :Descripción %><br>
      <%= form.text_field :description, class: 'form-control', placeholder: 'Escribir descripción' %>
  </div>
   
  <div class="form-group">
    <%= form.submit 'Crear Opción', class: 'w-100 btn btn-success'%>
    <a class="btn btn-secondary btn-md btn-block" style="margin-top:5px" href="<%= election_path(@proposal.election_id) %>">Volver</a> 
  </div>
<% end %>

app/views/options/_option.html.erb
<p>
<strong>Opción:</strong>
<%= option.description %>
</p>