config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  # Default page after login (except redirection from email)
  root to: "home#index"

  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  resources :vote, :home, :support, :about
  resources :users
 
  resources :elections do
    resources :proposals 
  end
  resources :proposals do
    resources :options
  end

  # Home
  get '/user' => "home#index", :as => :user_root

  # Election
  get '/elections/:id', to: 'elections#show'
  get '/elections', to: 'elections#index'
  post '/elections', to: 'elections#create'
  get  '/elections/new', to: 'elections#new'
  post '/options', to: 'options#create'
  get '/elections/results/:electionId', to: 'elections#results'
  get '/elections/info/:electionId', to: 'elections#info'
  get '/elections/activate_election/:electionId', to: 'elections#activate_election'

  # Vote
  get '/vote/new/:electionId' => 'vote#new', :as => :email_vote
  get '/elections/results/:electionId' => 'elections#results', :as => :email_results
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/election.rb
class Election < ApplicationRecord
  enum segmented_by: [:city, :state, :age]
  has_many :proposals, dependent: :destroy
  accepts_nested_attributes_for :proposals
  belongs_to :user
  has_many :user_elections
  has_many :users_that_vote, through: :user_elections, source: :user

  validates :description, :start_date, :finish_date, :segmented_by, :condition, presence: true
  validate :date_after_today, :start_before_finish

  private

  def date_after_today
    return unless start_date.present? && start_date < Date.current

    error_message = 'Fecha de inicio debe ser posterior a la actual'
    errors.add(:start_date, error_message)
  end

  def start_before_finish
    return unless start_date.present? && finish_date.present? && start_date > finish_date

    error_message = 'Fecha de inicio debe ser anterior a la fecha de fin'
    errors.add(:start_date, error_message)
  end
end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
  before_action :authenticate_user!
  
    def index
      @elections = Election.all
    end
   
    def show
      @election = Election.find(params[:id])
    end

    def results
      @election = Election.find(params[:electionId])
      return
    end

    def info
      @election = Election.find(params[:electionId])
    end
   
    def activate_election
      @election = Election.find(params[:electionId])
      if @election.activated == nil || @election.activated == false

        @election = @election.update_attribute(:activated, true)
        return
      end
    end

    helper_method :has_finish
    helper_method :has_started
    helper_method :election_status
    helper_method :activate_status_2

    # Returns true if it is closed, or false if not finished yet
    def has_finish(electionId)
      @election = Election.find(electionId)
      (@election.finish_date.to_i - Time.now.to_i) <= 0
    end

    # Returns true if the election has already opened, or false if the date was not reached
    def has_started(electionId)
      @election = Election.find(electionId)
      (Time.now.to_i - @election.start_date.to_i) >= 0
    end
    
    # Returns a status number for an election
      # 4 is activated and closed
      # 3 is activated and not closed
      # 2 is not activated with proposals (options controlled in activate_state_2 method)
      # 1 is not activated without proposals
    def election_status(electionId)
      @election = Election.find(electionId)  
      if @election.activated and has_finish(electionId)
        4
      elsif @election.activated and !has_finish(electionId)
        3
      elsif !@election.activated
        if @election.proposals.length == 0
          1
        else
          2
        end
      end
    end

    # Returns true if each of the proposals has at least one option
    def activate_status_2(electionId)
      @election = Election.find(electionId)  
      @result = true
      @election.proposals.each do |proposal|
        if proposal.options.length == 0
          @result = false
          break
        end
      end
      @result
    end

    def create
      @election = Election.new(election_params)
      if @election.save
        redirect_to election_path(@election)
      else 
        render :new
      end
    end 

    private
    def election_params
      params.require(:election).permit(:id, :description, :start_date, :finish_date, :user_id, :segmented_by, :condition, :created_at, :updated_at, :activated)
    end
end

app/views/elections/activate_election.html.erb
<div class="container col-6">
    <div class="py-4">
        <h4><span class="d-flex justify-content-center align-items-center text-secondary mt-3">La elección fue activada!</span></h4>
        <hr class="mb-4">
        <a class="btn btn-success btn-lg btn-block mr-3" href="/elections">Volver al Listado</a>
    </div>
</div>

app/views/elections/index.html.erb
<div class="container col-12">
  <h2 class="d-flex justify-content-between align-items-center mb-3">
    <h2><span class="shadow-lg badge badge-secondary">Listado de Elecciones</span></h2>
  </h2>
  
  <div class="div-formpage table-responsive shadow-lg">
    <table class="table table-md table-bordered">
      <thead class="thead-dark">
        <th style="text-align:center" scope="col">Descripción</th>
        <th style="text-align:center" scope="col">Segmentación</th>
        <th style="text-align:center" scope="col">Condición</th>
        <th style="text-align:center" scope="col">Fecha Inicio / Fecha Fin</th>
        <th style="text-align:center" scope="col">Mas Información</th>
        <th style="text-align:center" scope="col">Propuestas y Opciones</th>
        <th style="text-align:center" scope="col">Estado</th>
        <th style="text-align:center" scope="col">Resultados</th>
      </thead>
      <tbody>
        <% @elections.each do |election| %>
          <tr>
            <td><%= election.description %></td>
            <% if election.segmented_by == 'state' %>
              <td style="text-align:center"> Departamento </td>
            <% end%>
            <% if election.segmented_by == 'city' %>
              <td style="text-align:center"> Ciudad </td>
            <% end%>
            <% if election.segmented_by == 'age' %>
              <td style="text-align:center"> Edad </td>
            <% end%>
            <td style="text-align:center"><%= election.condition %></td>
            <td style="text-align:center"><small><%= "#{l(election.start_date, format: '%d/%m/%Y %H:%M')}" " -- " "#{l(election.finish_date, format: '%d/%m/%Y %H:%M')}" %></small></td>
            <td style="text-align:center">
              <%= link_to "Ver", "/elections/info/#{election.id}", class: "text-white btn btn-secondary btn-sm btn-block" %>
            </td>

            <% if election.activated || has_finish(election.id) %>
              <td class="text-dark" style="text-align:center">No permitido</td>
            <% else %>
              <td style="text-align:center">
                <%= link_to "Agregar", election_path(election), class: "text-white btn btn-success btn-sm btn-block" %>
              </td>
            <% end %>

            <% if election_status(election.id) == 4 %>
              <td class="text-secondary" style="text-align:center">Cerrada</td>
              <td style="text-align:center">
                <%= link_to "Ver Resultados", "/elections/results/#{election.id}", class: "text-white btn btn-success btn-sm btn-block" %>
              </td>
            <% elsif election_status(election.id) == 3 %>
              <% if has_started(election.id) %>
                <td class="text-secondary" style="text-align:center">Abierta</td>
              <% else %>
                <td class="text-success" style="text-align:center">Activada</td>
              <% end %>
              <td class="text-dark" style="text-align:center">No disponible</td>
            <% elsif election_status(election.id) == 2 %>
              <% if activate_status_2(election.id) %>
                <td style="text-align:center">
                  <%= link_to "Activar", "/elections/activate_election/#{election.id}", class: "text-white btn btn-danger btn-sm btn-block" %>
                </td>
                <td class="text-dark" style="text-align:center">No disponible</td>
              <% else %>
                <td class="text-info" style="text-align:center">Incompleta</td>  
                <td class="text-dark" style="text-align:center">No disponible</td>
              <% end %>
            <% else %>
              <td class="text-info" style="text-align:center">Incompleta</td>  
              <td class="text-dark" style="text-align:center">No disponible</td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/elections/info.html.erb
<div class="container">
  <div class="py-2">
    
    <div id="top" class="col-md-12">
      <div class="row">
        <div class="col-md-12 mb-3">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <h3><span class="shadow-lg badge badge-success">Información de la Elección</span></h3>
          </h4>
          <ul class="shadow-lg list-group mb-3">
            <li class="list-group-item justify-content-between lh-condensed">
              <div>
                <h7>
                  <span class="text-dark font-weight-bold">Descripción: </span>
                  <span class="text-dark"><%= @election.description %></span>
                </h7>
              </div>
            </li>
          </ul>
          <hr class="mb-4">
        </div>
      </div>
    </div>
    
    <div id="bottom" class="col-md-12 order-md-2 visible">
      <div class="row">
        <div class="col-md-12 mb-3">
          <form class="needs-validation" novalidate>   
            <% if @election.proposals.length != 0 %>
              <h4><span class="shadow-lg badge badge-success">Datos de cada Propuesta</span></h4>
              
                <% @election.proposals.each do |proposal| %>

                  <li class="mt-2 list-group-item list-group-item-white justify-content-center lh-condensed">
                    <div class="text-success">
                      <h6>
                        <span class="text-secondary">Nombre de la propuesta: </span>
                        <span class="text-success font-weight-bold"><%= proposal.name %></span>
                      </h6>
                      <h7>
                        <span class="text-secondary font-weight-bold">Descripción: </span>
                        <span class="text-success"><%= proposal.description %></span>
                      </h7>

                      <% if proposal.options.length !=0 %>
                        <table class="table table-bordered table-sm mt-3 shadow-lg">
                            <thead class="thead-dark">
                              <th style="text-align:center" scope="col">Opciones</th>
                            </thead>
                            <% proposal.options.each do |option| %>
                                <tbody>  
                                  <td class="table-secondary" style="text-align:center"><%= option.description %></td>
                                </tbody>
                            <% end %>
                        </table>
                      <% end %>
                    </div>
                  </li>
                <% end %>
              </ul>
              <hr class="mb-4">
            <% else %>
              <h5><span class="d-flex justify-content-center align-self-center text-secondary">La elección no tiene propuestas</span></h5>
            <% end %>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/elections/new.html.erb
<div class="container col-6 py-4">
  
  <%= form_with scope: :election, url: elections_path, local: true do |form| %>
    

    <% if @election.present? && @election.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @election.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row">
      <div class="col-sm-6 py-3">
          <h1><span class="shadow-lg badge badge-secondary">Agregar Elección</span></h1>
      </div>
      <div class="col-sm-6">
        <%= form.number_field :user_id, value: current_user.id, class: 'form-control invisible', :readonly => true%>
      </div>
    </div>
    <hr class="mb-4">

    <div class="form-group mt-3">
          <%= form.label :description, 'Descripción'  %><br>
          <%= form.text_field :description, class: 'form-control', placeholder: 'Escribir descripción'  %>
    </div>

    <div class="form-group row">
      <div class="col-sm-6 col-sm-2">
        <%= form.label :start_date, 'Fecha de comienzo'%>
        <%= form.datetime_field :start_date, start_year: 2020, class: 'form-control list-inline-item text-success' %>
      </div>
      <div class="col-sm-6">
        <%= form.label :finish_date, 'Fecha de finalización' %>
        <%= form.datetime_field :finish_date, start_year: 2020, class: 'form-control list-inline-item text-success' %>
        </div>
    </div>

    <div class="form-group">
      <%= form.label :segmented_by, 'Segmentado por: '%>
      <%= form.select (:segmented_by), 
      options_for_select([ 
        ['Ciudad', 'city'],
        ['Departamento','state'],
        ['Edad','age'],
      ]), {}, {class: 'form-control'} %> 
    </div>
    <div class="form-group">
      <%= form.label :condition, 'Condición '%>
      <%= form.select (:condition), 
      options_for_select(city_options), {}, {class: 'form-control'} %> 
    </div>
    <hr class="mb-4">
    <div class="form-group">
      <%= form.submit 'Guardar', class: 'w-100 btn btn-success'%>
      <a class="btn btn-secondary btn-md btn-block" style="margin-top:5px" href="/home">Volver</a> 
    </div> 
  <% end %>
</div>

<script>
  $(document).on('turbolinks:load', function() {
    $('#election_segmented_by').change(function() {
      var items;
      var segmented_by = document.getElementById("election_segmented_by").value;
      if (segmented_by === "state"){
        items = ['Artigas', 'Canelones', 'Cerro Largo', 'Colonia', 'Durazno', 'Flores', 'Florida', 'Lavalleja', 'Maldonado', 'Montevideo', 'Paysandú', 
                 'Río Negro', 'Rivera', 'Rocha', 'Salto', 'San José', 'Soriano', 'Tacuarembó', 'Treinta y Tres'];
      } else if (segmented_by === "age") {
        items = ['18-30', '31-40', '41-50', '51-60', '61 y mas'];
      } else if (segmented_by === "city"){
        items = ['Artigas', 'Canelones', 'Colonia del Sacramento', 'Durazno', 'Florida', 'Fray Bentos', 
                 'Maldonado', 'Melo', 'Mercedes', 'Minas', 'Montevideo', 'Paysandú', 'Rivera', 'Rocha', 'Salto', 
                 'San José de Mayo', 'Tacuarembó', 'Treinta y Tres', 'Trinidad'
        ];
      }
      var options = "";
      for (var item of items) {
        options += "<option value=" + item + ">" + item + "</option>";
      }
      document.getElementById("election_condition").innerHTML = options;
    });
  });
</script>

app/views/elections/results.html.erb
<div class="container">
  <div class="py-2">
    
    <div id="top" class="col-md-12">
      <div class="row">
        <div class="col-md-12 mb-3">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <h3><span class="shadow-lg badge badge-success">Resultados de la Elección</span></h3>
          </h4>
          <ul class="shadow-lg list-group mb-3">
            <li class="list-group-item justify-content-between lh-condensed">
              <div>
                <h7>
                  <span class="text-dark font-weight-bold">Descripción: </span>
                  <span class="text-dark"><%= @election.description %></span>
                </h7>
              </div>
            </li>
          </ul>
          <hr class="mb-4">
        </div>
      </div>
    </div>
    
    <div id="bottom" class="col-md-12 order-md-2 visible">
      <div class="row">
        <div class="col-md-12 mb-3">
          <form class="needs-validation" novalidate>   
            <% if @election.proposals.length != 0 %>
              <h4><span class="shadow-lg badge badge-success">Resultados obtenidos en cada propuesta</span></h4>
              
                <% @election.proposals.each do |proposal| %>

                  <li class="mt-2 list-group-item list-group-item-success justify-content-center lh-condensed">
                    <div class="text-success">
                      <h6>
                        <span class="text-secondary">Nombre de la propuesta: </span>
                        <span class="text-success font-weight-bold"><%= proposal.name %></span>
                      </h6>
                      <h7>
                        <span class="text-secondary font-weight-bold">Descripción: </span>
                        <span class="text-success"><%= proposal.description %></span>
                      </h7>

                      <% if proposal.options.length !=0 %>
                        <table class="table table-bordered table-sm mt-3 shadow-lg">
                            <thead class="thead-dark">
                              <th style="text-align:center" scope="col">Opción</th>
                              <th style="text-align:center" scope="col">Cantidad de Votos</th>
                            </thead>
                            <% proposal.options.each do |option| %>
                                <tbody>  
                                  <td class="table-secondary" style="text-align:center"><%= option.description %></td>
                                  <td class="table-secondary" style="text-align:center"><%= @count = Vote.where(option_id: option.id).count %></td>
                                </tbody>
                            <% end %>
                        </table>
                      <% end %>
                    </div>
                  </li>
                <% end %>
              </ul>
              <hr class="mb-4">
            <% else %>
              <h5><span class="d-flex justify-content-center align-self-center text-secondary">La elección no tiene propuestas</span></h5>
            <% end %>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/elections/show.html.erb
<div class="container col-6">
  <h1 class="d-flex justify-content-between align-items-center mb-3">
    <h4><span class="shadow-lg badge badge-secondary">Datos de la Elección</span></h4>
  </h1>
  <hr class="mb-1">
  <div class="form-group">
  <strong>Descripción: </strong>
  <%= @election.description %>
  </div>

  <div class="form-group">
    <strong>Fecha de comienzo:</strong>
    <%= "#{l(@election.start_date, format: '%d/%m/%Y %H:%M')}" %>
  </div>

  <div class="form-group">
    <strong>Fecha finalización:</strong>
    <%= "#{l(@election.finish_date, format: '%d/%m/%Y %H:%M')}" %>
  </div>

  <div class="form-group">
    <strong>Usuario:</strong>
    <%= @election.user.email %>
  </div>

  <div class="form-group">
    <strong>Segmentado por:</strong>
    <% if @election.segmented_by == 'department' %>
      <div class="d-inline"> Departamento </div>
    <% end%>
    <% if @election.segmented_by == 'city' %>
      <div class="d-inline"> Ciudad </div>
    <% end%>
    <% if @election.segmented_by == 'age' %>
      <div class="d-inline"> Edad </div>
    <% end%>
  </div>

  <div class="form-group">
  <strong>Condición: </strong>
  <%= @election.condition %>
</div>
<hr class="mb-3">

<% if @election.proposals.length != 0 %>
  <h1 class="d-flex justify-content-between align-items-center mb-3">
      <h4><span class="shadow-lg badge badge-secondary">Propuestas de la Elección</span></h4>
  </h1>
  <hr class="mb-2">
  <div class="div-formpage table-responsive shadow-md">
    <table class="table table-bordered">
      <thead class="thead-dark">
        <th style="text-align:center" scope="col">Nombre</th>
        <th style="text-align:center" scope="col">Descripción</th>
        <th style="text-align:center" scope="col">Opciones</th>
      </thead>
      <tbody>
        <%= render @election.proposals %>
      </tbody>
    </table>
  </div>
<% end %>
<% if @election.proposals.length == 0 %>
  <h1 class="d-flex justify-content-between align-items-center mb-3">
      <h5><span class="shadow-xs text-secondary">Actualmente la elección no tiene propuestas</span></h5>
  </h1>
<% end %>
<hr class="mb-3">


<h1 class="d-flex justify-content-between align-items-center mb-3">
    <h4><span class="shadow-lg badge badge-secondary">Agregar una Propuesta</span></h4>
</h1>
<hr class="mb-1">
<%= render 'proposals/form' %>

</div>