config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  # Default page after login (except redirection from email)
  root to: "home#index"

  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  resources :vote, :home, :support, :about
  resources :users
 
  resources :elections do
    resources :proposals 
  end
  resources :proposals do
    resources :options
  end

  # Home
  get '/user' => "home#index", :as => :user_root

  # Election
  get '/elections/:id', to: 'elections#show'
  get '/elections', to: 'elections#index'
  post '/elections', to: 'elections#create'
  get  '/elections/new', to: 'elections#new'
  post '/options', to: 'options#create'
  get '/elections/results/:electionId', to: 'elections#results'
  get '/elections/info/:electionId', to: 'elections#info'
  get '/elections/activate_election/:electionId', to: 'elections#activate_election'

  # Vote
  get '/vote/new/:electionId' => 'vote#new', :as => :email_vote
  get '/elections/results/:electionId' => 'elections#results', :as => :email_results
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :option
end

app/controllers/vote_controller.rb
class VoteController < ApplicationController
    before_action :authenticate_user!
    helper_method :can_vote

    def index
        @vote = Vote.all
    end

    def show
        @vote = Vote.find(params[:id])
    end

    def new 
        @election = Election.find(params[:electionId])
        @has_proposals = @election.proposals.count > 0
        @can_vote = can_vote(@election.id)
        @user_already_vote = user_alredy_vote(@election.id)
        @user_can_vote = validate_segmentation(@election.id)
    end
    
    def create
        @election = Election.find(params[:electionId])
        @voteDate = DateTime.current()
        votes = params[:optionsId].split(',')
        @user = User.find(current_user.id) #current_user
        @user_can_vote = user_can_vote(@election.id)
        
        if !@user_can_vote
            flash.alert = "El usuario no puede votar esta elección"
            return
        end

        unless @election.users_that_vote.include?(@user)
            votes.each do |optionId|
                @vote = Vote.new({option_id: optionId, vote_date: @voteDate})
                @vote.save
            end
            @user.elections_voted << @election
        end
        
        #redirect_to vote_path(@vote)
    end

    private

    def vote_params
        params.require(:optionId)
    end

    # Returns true if the election is in the open voting period, false for the contrary
    def can_vote(electionId)
        @election = Election.find(electionId)
        @start = Time.now.to_i - @election.start_date.to_i
        @finish = @election.finish_date.to_i - Time.now.to_i
        if @finish > 0 and @start > 0
        true
        else
        false
        end
    end

    def user_can_vote(electionId)
        return !user_alredy_vote(electionId) && validate_segmentation(electionId)
    end

    def user_alredy_vote(electionId)
        @voteElection = UserElection.where(user_id: current_user.id, election_id: electionId)
        if @voteElection.empty?
            return false
        else
            return true
        end
    end

    def validate_segmentation(electionId)
        @user = User.find(current_user.id)
        @election = Election.find(electionId)
        @segmented_by = @election.segmented_by
        
        case @segmented_by
        when 'city'
            if @user.city != @election.condition
                return false
            end
        when 'state'
            if @user.state != @election.condition
                return false
            end
        when 'age'
            return age_in_range(@user.birth_date, @election.condition)
        else
            return false
        end
        return true
    end

    # date parameter is user birthdate, range parameter is a string with election range like (30-45) or (61 and more)
    def age_in_range(date, range)
        @age = ((Time.zone.now - date.to_time) / 1.years.seconds).to_i
        @election_range = range.split('-')
        if @election_range.length > 1       # commom case like (30-45)
            return !(@age < @election_range[0].to_i || @age > @election_range[1].to_i)
        else                                # case 61 or more
            return @age >= 61
        end
    end

end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/vote/new.html.erb
<div class="container">
  <div class="py-2">
    
    <div id="top" class="col-md-12">
      <div class="row">
        <div class="col-md-12 mb-3">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <h3><span class="shadow-lg badge text-success">Elección seleccionada</span></h3>
          </h4>
          <ul class="shadow-lg list-group mb-3">
            <li class="list-group-item justify-content-between lh-condensed bg-dark">
              <div>
                <h7>
                  <span class="text-white font-weight-bold">Descripción: </span>
                  <span class="text-white"><%= @election.description %></span>
                </h7>
              </div>
            </li>
          </ul>
          <h6 align="right" class="invisible" id="remaining">Cierre de votación en: <span class="text-success font-weight-bold" id="countdown"></span></h6>
          <hr class="mb-4">
        </div>
      </div>
    </div>

    <div id="bottom" class="col-md-12 order-md-2">
      <div class="row">
        <div class="col-md-12 mb-3">
          <h3 class="invisible mt-3" id="thanks"><span class="d-flex justify-content-center align-self-center text-white shadow-lg badge badge-success blink_me">Gracias por participar!</span></h3>
          <form class="needs-validation" novalidate> 
            <% if @user_already_vote %>
              <h3><span class="d-flex justify-content-center align-self-center text-white shadow-lg badge badge-danger blink_me">Usted ya votó en esta elección</span></h3>    
            <% else %>
              <% if @user_can_vote %>
                <% if @can_vote %> 
                  <% if @has_proposals %>
                    <h4><span class="shadow-lg badge badge-secondary">Propuestas y Opciones de Voto</span></h4>
                    <ul class="shadow-lg list-group mb-3">
                      <% @election.proposals.each do |proposal| %>
                        <li class="list-group-item justify-content-between lh-condensed">
                          <div class="text-success">
                            <h6>
                              <span class="text-secondary">Nombre de la propuesta: </span>
                              <span class="text-success font-weight-bold"><%= proposal.name %></span>
                            </h6>
                            <h7>
                              <span class="text-secondary font-weight-bold">Descripción: </span>
                              <span class="text-success"><%= proposal.description %></span>
                            </h7>
                            <div class="py-3">
                              <small class="text-secondary">Opciones de Voto: </small>
                              <select class="shadow-lg custom-select d-block options" id="Options" required>
                                <option value="-1" disabled selected>Click para desplegar...</option>
                                <% proposal.options.each do |option| %>
                                  <option value="<%= option.id %>"><%= option.description %></option>
                                <% end %>
                              </select>
                              <div class="invalid-feedback">La opción seleccionada no es correcta</div>
                            </div>
                          </div>
                        </li>
                      <% end %>
                    </ul>
                    <hr class="mb-4">
                    <button type="button" id="vote_button" class="shadow-lg btn btn-success btn-lg btn-block" data-toggle="modal" onClick="preVote()" data-target="#confirmarVotoModal">Votar</button>
                    <a class="btn btn-secondary btn-lg btn-block" href="/home">No Votar</a> 
                  <% else %>
                    <h5><span class="d-flex justify-content-center align-self-center text-secondary">La elección no tiene propuestas para votar</span></h5>
                  <% end %>
                <% else %>
                  <h5><span class="d-flex justify-content-center align-self-center text-secondary">La elección no se encuentra dentro del período habilitado para votar</span></h5>
                <% end %>
              <% else %>
                <h5><span class="d-flex justify-content-center align-self-center text-white shadow-lg badge badge-info blink_me">El usuario no cumple con los criterios de segmentación</span></h5>    
              <% end %>
            <% end %>
          </form>
        <h6 class="visible mt-2" id="dont-forget"><span class="d-flex justify-content-center align-self-center text-secondary">Antes de salir de esta ventana procure cerrar correctamente su sesión</span></h6>
        </div>
      </div>                  
    </div> 

    <!-- Modal -->
    <div class="modal fade" id="confirmarVotoModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="">Votar Propuesta</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <%= form_with scope: :vote, url: vote_index_path, local: true do |form| %>
            <%= hidden_field :election, :id %>
          <div class="modal-body">
            <p>¿Confirma la votación de las opciones?</p>
            <p class="text-danger">Recuerde que esta acción NO se puede deshacer</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-success" data-dismiss="modal" onClick="postVote()">Confirmar</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
          </div>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

<script>
    var end = new Date('<%= @election.finish_date %>');
    var start = new Date('<%= @election.start_date %>');

    var _second = 1000;
    var _minute = _second * 60;
    var _hour = _minute * 60;
    var _day = _hour * 24;
    var timer;

    // This function verifies that all checkboxes have option selected
    function preVote() {
      const host = $(window)[0].location.origin
      const optionsObjects = document.getElementsByClassName('options');

      for  (i = 0; i < optionsObjects.length; i++) {
        const obj = optionsObjects[i]
        if (obj.options[obj.selectedIndex].value == "-1") {
          alert("ATENCIÓN:\nDebe seleccionar al menos una opción en cada una de las propuestas disponibles")
          $('button[id^="vote_button"]').removeAttr('data-target');
          return;
        }
        $('button[id^="vote_button"]').attr("data-target", "#confirmarVotoModal");
        return;
      }
    }

    function postVote() {
      const host = $(window)[0].location.origin
      const optionsObjects = document.getElementsByClassName('options');
      const length = optionsObjects.length
      var optionsId = [];
      const electionId = document.getElementById('election_id').value;

      for  (i = 0; i < length; i++) {
        const obj = optionsObjects[i]
        optionsId.push(obj.options[obj.selectedIndex].value)
      }
      let formData = new FormData();

      formData.append('authenticity_token', $("[name='authenticity_token']").val());
      formData.append('optionsId', optionsId);
      formData.append('electionId', electionId)

      fetch(`${host}/vote`, { method: 'POST', body: formData })
      .then( console.log('Everything was fine!'))

      $('div[id^="bottom"]').removeClass('visible').addClass('invisible');
      $('h3[id^="thanks"]').removeClass('invisible').addClass('visible');
    }

    function showRemaining() {
        var now = new Date();
        var distance = end - now;
        if (distance < 0) {

            clearInterval(timer);
            document.getElementById('countdown').innerHTML = 'LA VOTACION YA CERRÓ';

            return;
        }
        var days = Math.floor(distance / _day);
        var hours = Math.floor((distance % _day) / _hour);
        var minutes = Math.floor((distance % _hour) / _minute);
        var seconds = Math.floor((distance % _minute) / _second);

        document.getElementById('countdown').innerHTML = days + ' dias, ';
        document.getElementById('countdown').innerHTML += hours + ' horas, ';
        document.getElementById('countdown').innerHTML += minutes + ' minutos y ';
        document.getElementById('countdown').innerHTML += seconds + ' segundos';
        
        // We prevent the sample of proposals if the voting is closed
        if ((now - start) > 0 ) {
          $('h6[id^="remaining"]').removeClass('invisible').addClass('visible');
        }
    }

    timer = setInterval(showRemaining, 1000);
</script>