config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  # Default page after login (except redirection from email)
  root to: "home#index"

  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  resources :vote, :home, :support, :about
  resources :users
 
  resources :elections do
    resources :proposals 
  end
  resources :proposals do
    resources :options
  end

  # Home
  get '/user' => "home#index", :as => :user_root

  # Election
  get '/elections/:id', to: 'elections#show'
  get '/elections', to: 'elections#index'
  post '/elections', to: 'elections#create'
  get  '/elections/new', to: 'elections#new'
  post '/options', to: 'options#create'
  get '/elections/results/:electionId', to: 'elections#results'
  get '/elections/info/:electionId', to: 'elections#info'
  get '/elections/activate_election/:electionId', to: 'elections#activate_election'

  # Vote
  get '/vote/new/:electionId' => 'vote#new', :as => :email_vote
  get '/elections/results/:electionId' => 'elections#results', :as => :email_results
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  has_many :options, dependent: :destroy
  accepts_nested_attributes_for :options
  belongs_to :election
  validates :name, :description, presence: true
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @election = Election.find(params[:election_id])
    @proposal = @election.proposals.create(proposal_params)
    redirect_to election_path(@election)
  end

  def show
    @proposal = Proposal.find(params[:id])
  end
 
  private
  
  def proposal_params
    params.require(:proposal).permit(:name, :description, :election_id)
  end
end

app/views/proposals/_form.html.erb
<%= form_with(model: [ @election, @election.proposals.build ], local: true) do |form| %>
  <div class="form-group">
      <%= form.label :Nombre %><br>
      <%= form.text_field :name, class: 'form-control', placeholder: 'Escribir nombre' %>
  </div>
  <div class="form-group">
      <%= form.label :Descripción %><br>
      <%= form.text_area :description, class: 'form-control', placeholder: 'Escribir descripción' %>
  </div>
  <div class="form-group">     
    <%= form.submit 'Crear Propuesta', class: 'w-100 btn btn-success'  %> 
    <a class="btn btn-secondary btn-md btn-block" style="margin-top:5px" href="/elections">Volver</a> 
  </div>
<% end %>

app/views/proposals/_proposal.html.erb
<tr>
  <td style="text-align:center"><%= proposal.name %></td>
  <td style="text-align:center"><%= proposal.description %></td>
  <td style="text-align:center"><%= link_to 'Agregar Opciones', proposal_path(proposal), class: "text-white btn btn-success btn-sm btn-block" %></td>
</tr>

app/views/proposals/show.html.erb
<div class="container col-6">
  <h1 class="d-flex justify-content-between align-items-center mb-3">
    <h4><span class="shadow-lg badge badge-secondary">Datos de la Propuesta</span></h4>
  </h1>
  <hr class="mb-1">

  <div class="form-group">
    <strong>Título:</strong>
    <%= @proposal.name %>
  </div>

  <div class="form-group">
    <strong>Descripción:</strong>
    <%= @proposal.description %>
  </div>
  <hr class="mb-3">

  <h1 class="d-flex justify-content-between align-items-center mb-3">
    <h4><span class="shadow-lg badge badge-secondary">Opciones de la Propuesta</span></h4>
  </h1>
  <hr class="mb-1">
  <%= render @proposal.options %>
 
  <h1 class="d-flex justify-content-between align-items-center mb-3">
    <h4><span class="shadow-lg badge badge-secondary">Agregar una Opción</span></h4>
  </h1>
  <hr class="mb-1">
  <%= render 'options/form' %>
</div>